DROP VIEW IF EXISTS VW_CURSO_AULA;
CREATE VIEW VW_CURSO_AULA
AS
SELECT
CURAU.CD_CURSO_AULA,
CURAU.CURAU_TITULO,
CURAU.CURAU_DESCRICAO,
CURAU.CURAU_AULA,
CURAU.CURAU_FL_CURSO_AULA_ATIVO_SN, 
CURAU.CURAU_DT_AUDITORIA_ALTERACAO,
CURAU.CURAU_DS_AUDITORIA_LOGIN,
CURAU.CURAU_VIDEO,

CURAU.CD_CURSO,
CUR.CUR_TITULO

FROM
T_CURSO_AULA as CURAU

LEFT JOIN T_CURSO as CUR
ON CUR.CD_CURSO = CURAU.CD_CURSO;

