DROP VIEW IF EXISTS VW_LINGUAGEM_PROGRAMACAO;
CREATE VIEW VW_LINGUAGEM_PROGRAMACAO
AS
SELECT
    LP.LP_NOME,
    LP.LP_FL_LINGUAGEM_PROGRAMACAO_ATIVO_SN,
    LP.LP_DT_AUDITORIA_ALTERACAO,
    LP.LP_DS_AUDITORIA_LOGIN,

FROM
T_LINGUAGEM_PROGRAMACAO as LP;





