DROP VIEW IF EXISTS VW_MATRICULA;
CREATE VIEW VW_MATRICULA
AS
SELECT
    MA.MA_NOME,
    MA.MA_STATUS,
    MA.MA_DT_INICIO,
    MA.MA_DT_TERMINO,
    MA.MA_FL_MATRICULA_ATIVO_SN, 
    MA.MA_DT_AUDITORIA_ALTERACAO,
    MA.MA_DS_AUDITORIA_LOGIN,

    US.CD_USUARIO,
    US.US_NOME,

    CUR.CD_CURSO,
    CUR.CUR_TITULO

FROM
T_MATRICULA as CUR

INNER JOIN T_USUARIO AS US
ON US.CD_USUARIO = CUR.CD_USUARIO

INNER JOIN T_CURSO AS CUR
ON CUR.CD_CURSO = CUR.CD_CURSO;
