DROP VIEW IF EXISTS VW_USUARIO;
CREATE VIEW VW_USUARIO
AS
SELECT
US.CD_USUARIO,
US.US_NOME,
US.US_LOGIN,
US.US_EMAIL,
US.US_SENHA,
US.US_DT_NASCIMENTO,
US.US_FL_USUARIO_ATIVO_SN,
US.US_DT_AUDITORIA_ALTERACAO,
US.US_AUDITORIA_LOGIN

FROM
T_USUARIO as US;
