DROP PROCEDURE IF EXISTS PR_T_PROFESSOR_DELETE;

DELIMITER $$
CREATE PROCEDURE PR_T_PROFESSOR_DELETE
(
IN _CD_PROFESSOR int(11)
)
BEGIN
DECLARE errno INT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
	GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
	SELECT errno AS MYSQL_ERROR;
	ROLLBACK;
END;

START TRANSACTION;

UPDATE T_PROFESSOR
SET
    FL_PROFESSOR_ATIVO_SN = 'N'
WHERE
    CD_PROFESSOR = _CD_PROFESSOR;
    
COMMIT WORK;

END$$
DELIMITER ;
