DROP PROCEDURE IF EXISTS PR_T_LINGUAGEM_PROGRAMACAO_INSERT;

DELIMITER $$
CREATE PROCEDURE PR_T_LINGUAGEM_PROGRAMACAO_INSERT
(
OUT _CD_LINGUAGEM_PROGRAMACAO int(11),
IN _LP_FL_LINGUAGEM_PROGRAMACAO_ATIVO_SN CHAR(1), 
IN _LP_DT_AUDITORIA_ALTERACAO DATETIME,
IN _LP_DS_AUDITORIA_LOGIN TEXT
)
BEGIN
DECLARE errno INT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
	GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
	SELECT errno AS MYSQL_ERROR;
	ROLLBACK;
END;

START TRANSACTION;

INSERT INTO T_LINGUAGEM_PROGRAMACAO
(
    LP_NOME,
    LP_FL_LINGUAGEM_PROGRAMACAO_ATIVO_SN,
    LP_DT_AUDITORIA_ALTERACAO,
    LP_DS_AUDITORIA_LOGIN
)
VALUES
(
    _LP_NOME,
    _LP_FL_LINGUAGEM_PROGRAMACAO_ATIVO_SN,
    _LP_DT_AUDITORIA_ALTERACAO,
    _LP_DS_AUDITORIA_LOGIN
);

COMMIT WORK;
SET
	_CD_LINGUAGEM_PROGRAMACAO = LAST_INSERT_ID();

END$$
DELIMITER ;


