DROP PROCEDURE IF EXISTS PR_T_USUARIO_INSERT;

DELIMITER $$
CREATE PROCEDURE PR_T_USUARIO_INSERT
(
OUT _CD_USUARIO int(11),
IN _US_LOGIN VARCHAR(20),
IN _US_EMAIL VARCHAR(60),
IN _US_SENHA VARCHAR(260),
IN _US_DT_NASCIMENTO date,
IN _US_FL_USUARIO_ATIVO_SN CHAR(1), 
IN _US_DT_AUDITORIA_ALTERACAO DATETIME,
IN _US_AUDITORIA_LOGIN TEXT
)
BEGIN
DECLARE errno INT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
	GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
	SELECT errno AS MYSQL_ERROR;
	ROLLBACK;
END;

START TRANSACTION;

INSERT INTO T_USUARIO
(
    US_LOGIN,
    US_EMAIL,
    US_SENHA,
    US_DT_NASCIMENTO,
    US_FL_USUARIO_ATIVO_SN, 
    US_DT_AUDITORIA_ALTERACAO,
    US_AUDITORIA_LOGIN
)
VALUES
(
    _US_LOGIN,
    _US_EMAIL,
    _US_SENHA,
    _US_DT_NASCIMENTO,
    _US_FL_USUARIO_ATIVO_SN, 
    _US_DT_AUDITORIA_ALTERACAO,
    _US_AUDITORIA_LOGIN
);

COMMIT WORK;
SET
	_CD_USUARIO = LAST_INSERT_ID();

END$$
DELIMITER ;
