DROP PROCEDURE IF EXISTS PR_T_USUARIO_DELETE;

DELIMITER $$
CREATE PROCEDURE PR_T_USUARIO_DELETE
(
IN _CD_USUARIO int(11)
)
BEGIN
DECLARE errno INT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
	GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
	SELECT errno AS MYSQL_ERROR;
	ROLLBACK;
END;

START TRANSACTION;

UPDATE T_USUARIO
SET
    FL_USUARIO_ATIVO_SN = 'N'
WHERE
    CD_USUARIO = _CD_USUARIO;
    
COMMIT WORK;

END$$
DELIMITER ;
