DROP PROCEDURE IF EXISTS PR_T_CURSO_AULA_UPDATE;

DELIMITER $$
CREATE PROCEDURE PR_T_CURSO_AULA_UPDATE
(
IN _CD_CURSO_AULA int(11),
IN _CURAU_TITULO VARCHAR(30),
IN _CURAU_DESCRICAO TEXT,
IN _CURAU_QT_AULA INT,
IN _CURAU_FL_CURSO_AULA_ATIVO_SN CHAR(1), 
IN _CURAU_DT_AUDITORIA_ALTERACAO DATETIME,
IN _CURAU_AUDITORIA_LOGIN TEXT,
IN _CD_LINGUAGEM_PROGRAMACAO INT,
IN _CD_PROFESSOR INT,
IN _CURAU_BL_IMG longblob,
IN _CURAU_NM_IMG varchar(100),
IN _CD_CURSO INT
)
BEGIN
DECLARE errno INT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
	GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
	SELECT errno AS MYSQL_ERROR;
	ROLLBACK;
END;

START TRANSACTION;

UPDATE T_CURSO_AULA
SET
	CURAU_TITULO = _CUR_TITULO,
    CURAU_DESCRICAO = _CUR_DESCRICAO,
    CURAU_QT_AULA = _CUR_QT_AULA,
    CURAU_FL_CURSO_AULA_ATIVO_SN = _CUR_FL_CURSO_AULA_ATIVO_SN,
    CURAU_DT_AUDITORIA_ALTERACAO = _CUR_DT_AUDITORIA_ALTERACAO,
    CURAU_DS_AUDITORIA_LOGIN = _CUR_DS_AUDITORIA_LOGIN,
	CD_LINGUAGEM_PROGRAMACAO = _CD_LINGUAGEM_PROGRAMACAO,
    CD_PROFESSOR = _CD_PROFESSOR,
    CURAU_BL_IMG = _CUR_BL_IMG,
    CURAU_NM_IMG = _CUR_NM_IMG,
    CD_CURSO = _CD_CURSO
WHERE
    CD_CURSO_AULA = _CD_CURSO_AULA;
    
COMMIT WORK;

END$$
DELIMITER ;
