DROP PROCEDURE IF EXISTS PR_T_CURSO_DELETE;

DELIMITER $$
CREATE PROCEDURE PR_T_CURSO_DELETE
(
IN _CD_CURSO int(11)
)
BEGIN
DECLARE errno INT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
	GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
	SELECT errno AS MYSQL_ERROR;
	ROLLBACK;
END;

START TRANSACTION;

UPDATE T_CURSO
SET
    FL_CURSO_ATIVO_SN = 'N'
WHERE
    CD_CURSO = _CD_CURSO;
    
COMMIT WORK;

END$$
DELIMITER ;
