DROP PROCEDURE IF EXISTS PR_T_PROFESSOR_UPDATE;

DELIMITER $$
CREATE PROCEDURE PR_T_PROFESSOR_UPDATE
(
IN _CD_PROFESSOR int(11),
IN _PRO_CPF VARCHAR(20),
IN _PRO_RG varchar(30),
IN _PRO_FL_PROFESSOR_ATIVO_SN CHAR(1), 
IN _PRO_DT_AUDITORIA_ALTERACAO DATETIME,
IN _PRO_DS_AUDITORIA_LOGIN TEXT,
IN _CD_USUARIO INT
)
BEGIN
DECLARE errno INT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
	GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
	SELECT errno AS MYSQL_ERROR;
	ROLLBACK;
END;

START TRANSACTION;

UPDATE T_PROFESSOR
SET
CD_PROFESSOR = _CD_PROFESSOR,
PRO_CPF = _PRO_CPF,
PRO_RG = _PRO_RG,
PRO_FL_PROFESSOR_ATIVO_SN = _PRO_FL_PROFESSOR_ATIVO_SN,
PRO_DT_AUDITORIA_ALTERACAO = _PRO_DT_AUDITORIA_ALTERACAO,
PRO_DS_AUDITORIA_LOGIN = _PRO_DS_AUDITORIA_LOGIN,
CD_USUARIO = _CD_USUARIO
WHERE
    CD_PROFESSOR = _CD_PROFESSOR;
    
COMMIT WORK;

END$$
DELIMITER ;



