DROP PROCEDURE IF EXISTS PR_T_MATRICULA_DELETE;

DELIMITER $$
CREATE PROCEDURE PR_T_MATRICULA_DELETE
(
IN _CD_MATRICULA int(11)
)
BEGIN
DECLARE errno INT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
	GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
	SELECT errno AS MYSQL_ERROR;
	ROLLBACK;
END;

START TRANSACTION;

UPDATE T_MATRICULA
SET
    FL_MATRICULA_ATIVO_SN = 'N'
WHERE
    CD_MATRICULA = _CD_MATRICULA;
    
COMMIT WORK;

END$$
DELIMITER ;
