DROP PROCEDURE IF EXISTS PR_T_LINGUAGEM_PROGRAMACAO_DELETE;

DELIMITER $$
CREATE PROCEDURE PR_T_LINGUAGEM_PROGRAMACAO_DELETE
(
IN _CD_LINGUAGEM_PROGRAMACAO int(11)
)
BEGIN
DECLARE errno INT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
	GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
	SELECT errno AS MYSQL_ERROR;
	ROLLBACK;
END;

START TRANSACTION;

UPDATE T_LINGUAGEM_PROGRAMACAO
SET
    LP_FL_LINGUAGEM_PROGRAMACAO_ATIVO_SN = 'N'
WHERE
    CD_LINGUAGEM_PROGRAMACAO = _CD_LINGUAGEM_PROGRAMACAO;
    
COMMIT WORK;

END$$
DELIMITER ;
