DROP PROCEDURE IF EXISTS PR_T_CURSO_AULA_UPDATE;

DELIMITER $$
CREATE PROCEDURE PR_T_CURSO_AULA_UPDATE
(
IN _CD_CURSO_AULA int(11),
IN _CURAU_TITULO VARCHAR(30),
IN _CURAU_DESCRICAO TEXT,
IN _CURAU_AULA INT,
IN _CURAU_TEMPO INT,
IN _CURAU_FL_CURSO_AULA_ATIVO_SN CHAR(1), 
IN _CURAU_DT_AUDITORIA_ALTERACAO DATETIME,
IN _CURAU_DS_AUDITORIA_LOGIN TEXT,
IN _CURAU_VIDEO varchar(100),
IN _CD_CURSO INT
)
BEGIN
DECLARE errno INT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
	GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
	SELECT errno AS MYSQL_ERROR;
	ROLLBACK;
END;

START TRANSACTION;

UPDATE T_CURSO_AULA
SET
	CURAU_TITULO = _CURAU_TITULO,
    CURAU_DESCRICAO = _CURAU_DESCRICAO,
    CURAU_AULA = _CURAU_AULA,
    CURAU_TEMPO = _CURAU_TEMPO,
    CURAU_FL_CURSO_AULA_ATIVO_SN = _CURAU_FL_CURSO_AULA_ATIVO_SN,
    CURAU_DT_AUDITORIA_ALTERACAO = _CURAU_DT_AUDITORIA_ALTERACAO,
    CURAU_DS_AUDITORIA_LOGIN = _CURAU_DS_AUDITORIA_LOGIN,
    CURAU_VIDEO = _CURAU_VIDEO,
    CD_CURSO = _CD_CURSO
WHERE
    CD_CURSO_AULA = _CD_CURSO_AULA;
    
COMMIT WORK;

END$$
DELIMITER ;
