DROP PROCEDURE IF EXISTS PR_T_PROFESSOR_INSERT;

DELIMITER $$
CREATE PROCEDURE PR_T_PROFESSOR_INSERT
(
OUT _CD_PROFESSOR int(11),
IN _PRO_CPF VARCHAR(20),
IN _PRO_RG varchar(30),
IN _PRO_FL_PROFESSOR_ATIVO_SN CHAR(1), 
IN _PRO_DT_AUDITORIA_ALTERACAO DATETIME,
IN _PRO_DS_AUDITORIA_LOGIN TEXT,
IN _CD_USUARIO INT
)
BEGIN
DECLARE errno INT;

DECLARE EXIT HANDLER FOR SQLWARNING
BEGIN
	GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
	SELECT errno AS MYSQL_ERROR;
	ROLLBACK;
END;

START TRANSACTION;

INSERT INTO T_PROFESSOR
(
    PRO_CPF,
    PRO_RG,
    PRO_FL_PROFESSOR_ATIVO_SN, 
    PRO_DT_AUDITORIA_ALTERACAO,
    PRO_DS_AUDITORIA_LOGIN,
    CD_USUARIO
)
VALUES
(
    _PRO_CPF,
    _PRO_RG,
    _PRO_FL_PROFESSOR_ATIVO_SN, 
    _PRO_DT_AUDITORIA_ALTERACAO,
    _PRO_DS_AUDITORIA_LOGIN,
    _CD_USUARIO
);

UPDATE T_USUARIO
SET
US_FL_PROFESSOR_SN = 'S'
WHERE CD_USUARIO = _CD_USUARIO;

COMMIT WORK;
SET
	_CD_PROFESSOR = LAST_INSERT_ID();

END$$
DELIMITER ;



