DROP PROCEDURE IF EXISTS PR_T_PROFESSOR_UPDATE;

DELIMITER $$
CREATE PROCEDURE PR_T_PROFESSOR_UPDATE
(
IN _CD_PROFESSOR int(11),
IN _PRO_LOGIN VARCHAR(20),
IN _PRO_EMAIL VARCHAR(60),
IN _PRO_SENHA VARCHAR(260),
IN _PRO_CPF VARCHAR(20),
IN _PRO_DR_NASCIMENTO date, 
IN _PRO_FL_PROFESSOR_ATIVO_SN CHAR(1), 
IN _PRO_DT_AUDITORIA_ALTERACAO DATETIME,
IN _PRO_DS_AUDITORIA_LOGIN TEXT
)
BEGIN
DECLARE errno INT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
	GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
	SELECT errno AS MYSQL_ERROR;
	ROLLBACK;
END;

START TRANSACTION;

UPDATE T_PROFESSOR
SET
PRO_LOGIN = _PRO_LOGIN,
PRO_EMAIL = _PRO_EMAIL,
PRO_SENHA = _PRO_SENHA,
PRO_CPF = _PRO_CPF,
PRO_DT_NASCIMENTO = _PRO_DT_NASCIMENTO,
PRO_FL_PROFESSOR_ATIVO_SN = _US_FL_PROFESSOR_ATIVO_SN,
PRO_DT_AUDITORIA_ALTERACAO = _PRO_DT_AUDITORIA_ALTERACAO,
PRO_DS_AUDITORIA_LOGIN = _PRO_AUDITORIA_LOGIN
WHERE
    CD_PROFESSOR = _CD_PROFESSOR;
    
COMMIT WORK;

END$$
DELIMITER ;



