DROP PROCEDURE IF EXISTS PR_T_LINGUAGEM_PROGRAMACAO_UPDATE;

DELIMITER $$
CREATE PROCEDURE PR_T_LINGUAGEM_PROGRAMACAO_UPDATE
(
IN _CD_LINGUAGEM_PROGRAMACAO int(11),
IN _LP_NOME VARCHAR(20),
IN _LP_FL_LINGUAGEM_PROGRAMACAO_ATIVO_SN CHAR(1),
IN _LP_DT_AUDITORIA_ALTERACAO DATETIME,
IN _LP_DS_AUDITORIA_LOGIN TEXT
)
BEGIN
DECLARE errno INT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
	GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
	SELECT errno AS MYSQL_ERROR;
	ROLLBACK;
END;

START TRANSACTION;

UPDATE T_LINGUAGEM_PROGRAMACAO
SET
LP_NOME = _LP_NOME,
LP_FL_LINGUAGEM_PROGRAMACAO_ATIVO_SN = _LP_FL_LINGUAGEM_PROGRAMACAO_ATIVO_SN,
LP_DT_AUDITORIA_ALTERACAO = _LP_DT_AUDITORIA_ALTERACAO,
LP_DS_AUDITORIA_LOGIN = _LP_DS_AUDITORIA_LOGIN
WHERE
    CD_LINGUAGEM_PROGRAMACAO = _CD_LINGUAGEM_PROGRAMACAO;
    
COMMIT WORK;

END$$
DELIMITER ;


