DROP PROCEDURE IF EXISTS PR_T_CURSO_AULA_DELETE;

DELIMITER $$
CREATE PROCEDURE PR_T_CURSO_AULA_DELETE
(
IN _CD_CURSO_AULA int(11)
)
BEGIN
DECLARE errno INT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
	GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
	SELECT errno AS MYSQL_ERROR;
	ROLLBACK;
END;

START TRANSACTION;

UPDATE T_CURSO_AULA
SET
    CUR_FL_CURSO_AULA_ATIVO_SN = 'N'
WHERE
    CD_CURSO_AULA = _CD_CURSO_AULA;
    
COMMIT WORK;

END$$
DELIMITER ;
