DROP PROCEDURE IF EXISTS PR_T_PROFESSOR_INSERT;

DELIMITER $$
CREATE PROCEDURE PR_T_PROFESSOR_INSERT
(
OUT _CD_PROFESSOR int(11),
IN _PRO_LOGIN VARCHAR(20),
IN _PRO_EMAIL VARCHAR(60),
IN _PRO_SENHA VARCHAR(260),
IN _PRO_CPF VARCHAR(20),
IN _PRO_DT_NASCIMENTO date,
IN _PRO_FL_PROFESSOR_ATIVO_SN CHAR(1), 
IN _PRO_DT_AUDITORIA_ALTERACAO DATETIME,
IN _PRO_DS_AUDITORIA_LOGIN TEXT
)
BEGIN
DECLARE errno INT;

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
	GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
	SELECT errno AS MYSQL_ERROR;
	ROLLBACK;
END;

START TRANSACTION;

INSERT INTO T_PROFESSOR
(
    PRO_LOGIN,
    PRO_EMAIL,
    PRO_SENHA,
    PRO_CPF,
    PRO_DT_NASCIMENTO,
    PRO_FL_PROFESSOR_ATIVO_SN, 
    PRO_DT_AUDITORIA_ALTERACAO,
    PRO_DS_AUDITORIA_LOGIN
)
VALUES
(
    _PRO_LOGIN,
    _PRO_EMAIL,
    _PRO_SENHA,
    _PRO_CPF,
    _PRO_DT_NASCIMENTO,
    _PRO_FL_PROFESSOR_ATIVO_SN, 
    _PRO_DT_AUDITORIA_ALTERACAO,
    _PRO_DS_AUDITORIA_LOGIN
);

COMMIT WORK;
SET
	_CD_PROFESSOR = LAST_INSERT_ID();

END$$
DELIMITER ;



