CREATE DEFINER=`root`@`localhost` PROCEDURE `PR_T_CURSO_AULA_INSERT`(
OUT _CD_CURSO_AULA int(11),
IN _CURAU_TITULO VARCHAR(30),
IN _CURAU_DESCRICAO TEXT,
IN _CURAU_AULA INT,
IN _CURAU_TEMPO INT,
IN _CURAU_FL_CURSO_AULA_ATIVO_SN CHAR(1), 
IN _CURAU_DT_AUDITORIA_ALTERACAO DATETIME,
IN _CURAU_DS_AUDITORIA_LOGIN TEXT,
IN _CURAU_VIDEO varchar(100),
IN _CD_CURSO INT
)
BEGIN
DECLARE errno INT;

DECLARE EXIT HANDLER FOR sqlwarning
BEGIN
	GET CURRENT DIAGNOSTICS CONDITION 1 errno = MYSQL_ERRNO;
	SELECT errno AS MYSQL_ERROR;
	ROLLBACK;
END;

START TRANSACTION;

INSERT INTO T_CURSO_AULA
(
    CURAU_TITULO,
    CURAU_DESCRICAO,
    CURAU_AULA,
    CURAU_TEMPO,
    CURAU_FL_CURSO_AULA_ATIVO_SN, 
    CURAU_DT_AUDITORIA_ALTERACAO,
    CURAU_DS_AUDITORIA_LOGIN,
    CURAU_VIDEO,
    CD_CURSO
)
VALUES
(
    _CURAU_TITULO,
    _CURAU_DESCRICAO,
    _CURAU_AULA,
    _CURAU_TEMPO,
    _CURAU_FL_CURSO_AULA_ATIVO_SN, 
    _CURAU_DT_AUDITORIA_ALTERACAO,
    _CURAU_DS_AUDITORIA_LOGIN,
    _CURAU_VIDEO,
    _CD_CURSO
);

COMMIT WORK;
SET
	_CD_CURSO_AULA = LAST_INSERT_ID();

END